### ISSUE TITLE
无法安装“taiyuuki.vscode-nes”扩展，因为它与当前 Visual Studio Code 版本不兼容(版本 1.70.0)。

### ISSUE THREAD

**Issue by panhengzhen888** [taiyuuki/vscode-nes#2]
安装提示：无法安装“taiyuuki.vscode-nes”扩展，因为它与当前 Visual Studio Code 版本不兼容(版本 1.70.0)。

**Comment by taiyuuki** [comment]
目前最低支持1.74.0，理论上是可以向更低版本兼容的，但因为1.74以前package配置更啰嗦，而我自己一直用最新版，所以没考虑过这个问题。
