### ISSUE TITLE
可以调命或者改无敌吗

### ISSUE THREAD

**Issue by qnk-lk** [taiyuuki/vscode-nes#5]
比如在vscodeNes.romPath中添加配置

**Comment by taiyuuki** [comment]
单个游戏是可以的，但每个游戏的金手指规则不一样，很难通过简单的配置来适配所有游戏。

**Comment by qnk-lk** [comment]
如何可以在vscodeNes中进行单独的金手指配置的话 改如何填写配置条件呢   有相关的文档或者链接吗？

**Comment by taiyuuki** [comment]
目前这个插件并没有添加金手指功能，但金手指的实现其实非常简单，例如超级马里奥的无敌金手指是079F-01-01，只需要将079F对应的内存值强行指定为01就可以了。也就是说，要使用金手指，需要你自己上网搜对应的金手指代码，其实并不是很方便使用，但既然你提出来了，后续我会考虑添加金手指功能。

**Comment by qnk-lk** [comment]
好的 谢谢！
